### PR TITLE
Use the whole screen estate for content

### PR DESCRIPTION
**Pull request by nebulade**
col-md-12 will already constrain the width accordingly.

### CODE REVIEW

**Comment by claudioc** [comment]
I need a moment to try it and see if this change would be a problem for anybody (after all, nobody in these years has never presented anything like that – even if it's simple).

**Comment by claudioc** [comment]
I tried it but I don't like how large the main column will become, making the text harder to read, imho.

Thank you anyway!

**Comment by gramakri** [comment]
@claudioc will you accept this patch with a config option?

**Comment by claudioc** [comment]
@gramakri Since you can change / override this behaviour at your pleasure using the `_style.css`, I don't think there is no need for a configuration option. Don't you think?

**Comment by gramakri** [comment]
@claudioc that works as well :+1:

**Pull request closed without merging**
