### PR TITLE
Fixes missing dev dependency "nodemon"

### PR DESCRIPTION
**Pull request by JSteunou**

### CODE REVIEW

**Comment by derhuerst** [comment]
Maybe a peer dependency?

**Comment by JSteunou** [comment]
nope. It really is a dev dependency.

**Comment by derhuerst** [comment]
Hm. I'd be in favor of making it a peer dependency, as it's clearly not needed for running tests, linting, etc. Also, for daemonizing, some people prefer different tools like [`forever`](https://www.npmjs.com/package/forever) or [`pm2`](http://pm2.keymetrics.io/).

**Comment by JSteunou** [comment]
I assume as it is in `npm scripts` it is a dev dependency. Why you could run `npm test` but not `npm start-dev` after a fresh install?

**Comment by derhuerst** [comment]
That's a valid point. But *testing* is clearly a thing that should be possible with the `devDependencies` installed, whereas daemonizing should imho not be part of npm scripts and therefore not in the `devDependencies`. But that's just my two cents.

**Comment by claudioc** [comment]
I think @JSteunou is right. If there is a `start-dev` which uses nodemon, there should also be `nodemon` in the devDependencies.

**Pull request merged**
