### PR TITLE
Add cloudron oauth support

### PR DESCRIPTION
**Pull request by gramakri**
This will probably go down the way of https://github.com/claudioc/jingo/pull/26 but I thought I will put this here anyway :-)

I made a Cloudron app for Jingo (https://github.com/cloudron-io/jingo-app). As part of the app, I added Cloudron OAuth2 support to Jingo. The patch itself is very straightforward. I haven't published the app to our store yet, so it's a little hard to see how the Jingo app looks like (since I am waiting for a logo - opened an issue for that).

### CODE REVIEW

**Comment by claudioc** [comment]
Thank you! As you thought, I don't think this is enough a general use case to merge it in master. I will for sure add this integration in the documentation though.

btw, I _love_ the `/test` you made in the project. Cool stuff.

Keeping this open until I update the README (or the wiki)

**Comment by gramakri** [comment]
@claudioc So I published the app to the store.

https://cloudron.io/appstore.html#li.cica.jingo

Thanks for all your work, really nice app! One thing I miss in the app is that there is no way to interact with the git repo i.e a user cannot git push/pull. For that, jingo will have to have a per-user simple ssh key management. It's easy to run a ssh server and expose it to the outside world in a Cloudron app. Until then, users have to be content with just the web ui and no git access :-) Let me know if think this is interesting and I can open an issue.

https://my-demo.cloudron.me is a demo cloudron (username: cloudron password: cloudron). I have installed jingo there if you want to see how it looks. If it's been uninstalled by someone (since it's a demo cloudron), feel free to install it ('App Store' in the nav bar).

**Comment by gramakri** [comment]
Please let me know if there is any interest in maintaining https://github.com/cloudron-io/jingo-app on your side. I can add you as admin to that repo.

**Comment by claudioc** [comment]
Hi @gramakri 

thank you very much for this (and for the nice little happening in twitter :dancers: ).

I don't have time and resource at the moment to maintain the jingo-app, though. 

Thanks!

**Comment by gramakri** [comment]
So, I am going to close this because 1.7.0 now supports LDAP. I made the Cloudron App now use LDAP instead of OAuth.

**Pull request closed without merging**
