### PR TITLE
Add ability to mount the application and static assets at url fragment

### PR DESCRIPTION
**Pull request by creynold**
* Added `mountpath` and `staticpath` to configuration options
  * Added `cssAsset`, `scriptAsset`, and `relHref` mixins to jade templates
    * `cssAsset` and `scriptAsset` prepend with the `staticpath`
    * `relHref` prepends `mountpath` to the uri and allows for `block` and attributes such as `class`
  * Modified the internal js to render links relative to the `mountpath`
  * Modified `style.css` so that the images load relative to the current directory

PR meant to add to issue #124

### CODE REVIEW

**Comment by claudioc** [comment]
Hi,

I am trying this PR but it doesn't seem to work. I am pretty sure – for example – that in `app.js` when we mount the routes, you are missing `mountPath` as the first parameter. Documentation is missing too (in the README) and I guess that the default mountPath should be '/' and not '' (which means that in the `config.js` we need a specialised getter for it.

I will fix the above problems and I think I will merge it but NOT activate it (or not document it) until I am pretty sure that nothing breaks. In this way you could also take a look at what I am doing.

I will be off for some days, maybe without a laptop, so maybe I will be again on this PR in a few days.

See ya!

**Comment by creynold** [comment]
Just so we're on the same page: are you talking about `app.use(...)`? If so let me explain how I was thinking about this being used:

In my NGINX configuration I simply have:
```nginx
location /wiki {
    proxy_pass http://localhost:6067/;
}
```
What this does is send requests relative to this path to the Jingo app. So for instance if one browses to `http://<domain>/wiki` Jingo will see `GET request for ''`. Similarly if one browses to `http://<domain>/wiki/wiki/home` Jingo will see `GET request for '/wiki/home'`.

In this way Jingo simply needs to make sure all of its URLs are constructed with respect to the mount point (`mountPath + route`) yet process requests relative to this mount point (`route`).

**Comment by claudioc** [comment]
Yes, you're right. I was just thinking about creating a general case that could also be used to "solve" the proxy issue. But this is not the case, indeed.

To make it work (on a fresh repository, just to se what could happen) I had to use a rewrite in the nginx configuration and ensure that the mountPath starts with a '/'. With this configuration "mysite/wiki" and "mysite/wiki/" work flowlessy.

```
        location /wiki {
          rewrite ^/wiki(/.*)$ $1 break;
          proxy_pass http://localhost:6067/;
        }
```

Without this, I got the browser asking for `GET //` or `GET //wiki/Home`.

For the reason above, I guess I am renaming this feature `proxyPath` because this is what it is for after all (I don't really see any other use case beside that).

Another thing: do you think we could just use the same value for the `staticPath` configuration too? I'd like to not use one more configuration variable if it really not necessary.

**Comment by creynold** [comment]
Yeah sure, I just added that in case it was wanted in the future. I have no qualms about sticking with a single directory, though.

**Comment by claudioc** [comment]
OK, I merged it manually and added tests, documentation and a [Wiki page](https://github.com/claudioc/jingo/wiki/Serve-Jingo-pages-from-a-directory-behind-a-reverse-proxy) for it. 

Released with 1.6.0

**Pull request closed without merging**
